export const CREATED_ROOM = 'CREATED_ROOM';
export const CREATING_ROOM = "CREATING_ROOM";
export const AUTHENTICATING_ROOM = "AUTHENTICATING_ROOM";
export const AUTHENTICATED_ROOM = "AUTHENTICATED_ROOM";
export const SET_USERNAME = "SET_USERNAME";